title: Distracted Fortune
url: "https://distractedfortune.com"
baseurl: ""

permalink: /:title/

theme: minima

exclude:
  - .jekyll-cache
  - .jekyll-metadata
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
  - content/
  - documentation/ # Excludes your internal documentation files
  - migration.py
  - src/           # Excludes your raw migration script assets
  - test/          # Excludes your test fixtures folder
  - vendor
